### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by ZohaibRamzan** [qipeng/gcn-over-pruned-trees#26]
I am using jupyter notebook on server.
I have preprocess a new dataset in the required format( i.e. tacred dataset) but i am getting MemoryError while training; 
bash train_gcn.sh 0
I show you some my dataset examples;

[{"id":109627235236557200,"docid":"WLP-Dataset-master_updated\/train\/protocol_205","relation":"Acts-on","token":["Soak","the","PVDF","membrane","in","100","%","methanol","for","1","-","2","minutes","then","rinse","2","-","3","times","with","deionized","water","."],"subj_start":0,"subj_end":0,"obj_start":2,"obj_end":3,"subj_type":"Action","obj_type":"Reagent","stanford_pos":["VB","DT","NN","NN","IN","CD","NN","NN","IN","CD","SYM","CD","NNS","RB","VB","CD","SYM","CD","NNS","IN","VBN","NN","."],"stanford_ner":["Action","O","Reagent","Reagent","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"],"stanford_head":[0,4,4,1,8,7,8,1,13,13,12,10,1,15,1,19,18,16,15,22,22,15,1],"stanford_deprel":["root","det","compound","obj","case","nummod","compound","obl","case","nummod","case","nmod","obl","advmod","conj","nummod","case","nmod","obl:tmod","case","amod","obl","punct"]},{"id":109627235236557200,"docid":"WLP-Dataset-master_updated\/train\/protocol_205","relation":"Site","token":["Soak","the","PVDF","membrane","in","100","%","methanol","for","1","-","2","minutes","then","rinse","2","-","3","times","with","deionized","water","."],"subj_start":0,"subj_end":0,"obj_start":7,"obj_end":7,"subj_type":"Action","obj_type":"Reagent","stanford_pos":["VB","DT","NN","NN","IN","CD","NN","NN","IN","CD","SYM","CD","NNS","RB","VB","CD","SYM","CD","NNS","IN","VBN","NN","."],"stanford_ner":["Action","O","O","O","O","O","O","Reagent","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"],"stanford_head":[0,4,4,1,8,7,8,1,13,13,12,10,1,15,1,19,18,16,15,22,22,15,1],"stanford_deprel":["root","det","compound","obj","case","nummod","compound","obl","case","nummod","case","nmod","obl","advmod","conj","nummod","case","nmod","obl:tmod","case","amod","obl","punct"]},{"id":109627235236557200,"docid":"WLP-Dataset-master_updated\/train\/protocol_205","relation":"Count","token":["Soak","the","PVDF","membrane","in","100","%","methanol","for","1","-","2","minutes","then","rinse","2","-","3","times","with","deionized","water","."],"subj_start":14,"subj_end":14,"obj_start":15,"obj_end":18,"subj_type":"Action","obj_type":"Numerical","stanford_pos":["VB","DT","NN","NN","IN","CD","NN","NN","IN","CD","SYM","CD","NNS","RB","VB","CD","SYM","CD","NNS","IN","VBN","NN","."],"stanford_ner":["O","O","O","O","O","O","O","O","O","O","O","O","O","O","Action","Numerical","Numerical","Numerical","Numerical","O","O","O","O"],"stanford_head":[0,4,4,1,8,7,8,1,13,13,12,10,1,15,1,19,18,16,15,22,22,15,1],"stanford_deprel":["root","det","compound","obj","case","nummod","compound","obl","case","nummod","case","nmod","obl","advmod","conj","nummod","case","nmod","obl:tmod","case","amod","obl","punct"]},{"id":109627235236557200,"docid":"WLP-Dataset-master_updated\/train\/protocol_205","relation":"Using","token":["Soak","the","PVDF","membrane","in","100","%","methanol","for","1","-","2","minutes","then","rinse","2","-","3","times","with","deionized","water","."],"subj_start":14,"subj_end":14,"obj_start":20,"obj_end":21,"subj_type":"Action","obj_type":"Reagent","stanford_pos":["VB","DT","NN","NN","IN","CD","NN","NN","IN","CD","SYM","CD","NNS","RB","VB","CD","SYM","CD","NNS","IN","VBN","NN","."],"stanford_ner":["O","O","O","O","O","O","O","O","O","O","O","O","O","O","Action","O","O","O","O","O","Reagent","Reagent","O"],"stanford_head":[0,4,4,1,8,7,8,1,13,13,12,10,1,15,1,19,18,16,15,22,22,15,1],"stanford_deprel":["root","det","compound","obj","case","nummod","compound","obl","case","nummod","case","nmod","obl","advmod","conj","nummod","case","nmod","obl:tmod","case","amod","obl","punct"]},{"id":109627235236557200,"docid":"WLP-Dataset-master_updated\/train\/protocol_205","relation":"Acts-on","token":["Soak","the","PVDF","membrane","in","100","%","methanol","for","1","-","2","minutes","then","rinse","2","-","3","times","with","deionized","water","."],"subj_start":14,"subj_end":14,"obj_start":2,"obj_end":3,"subj_type":"Action","obj_type":"Reagent","stanford_pos":["VB","DT","NN","NN","IN","CD","NN","NN","IN","CD","SYM","CD","NNS","RB","VB","CD","SYM","CD","NNS","IN","VBN","NN","."],"stanford_ner":["O","O","Reagent","Reagent","O","O","O","O","O","O","O","O","O","O","Action","O","O","O","O","O","O","O","O"],"stanford_head":[0,4,4,1,8,7,8,1,13,13,12,10,1,15,1,19,18,16,15,22,22,15,1],"stanford_deprel":["root","det","compound","obj","case","nummod","compound","obl","case","nummod","case","nmod","obl","advmod","conj","nummod","case","nmod","obl:tmod","case","amod","obl","punct"]},{"id":109627235236557200,"docid":"WLP-Dataset-master_updated\/train\/protocol_205","relation":"Measure","token":["Soak","the","PVDF","membrane","in","100","%","methanol","for","1","-","2","minutes","then","rinse","2","-","3","times","with","deionized","water","."],"subj_start":7,"subj_end":7,"obj_start":5,"obj_end":6,"subj_type":"Reagent","obj_type":"Concentration","stanford_pos":["VB","DT","NN","NN","IN","CD","NN","NN","IN","CD","SYM","CD","NNS","RB","VB","CD","SYM","CD","NNS","IN","VBN","NN","."],"stanford_ner":["O","O","O","O","O","Concentration","Concentration","Reagent","O","O","O","O","O","O","O","O","O","O","O","O","O","O","O"],"stanford_head":[0,4,4,1,8,7,8,1,13,13,12,10,1,15,1,19,18,16,15,22,22,15,1],"stanford_deprel":["root","det","compound","obj","case","nummod","compound","obl","case","nummod","case","nmod","obl","advmod","conj","nummod","case","nmod","obl:tmod","case","amod","obl","punct"]}]

Here is the error i got;
Finetune all embeddings.
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    loss = trainer.update(batch)
  File "/home/hz071/gcn-over-pruned-trees/model/trainer.py", line 80, in update
    logits, pooling_output = self.model(inputs)
  File "/home/hz071/.conda/envs/AG-GCNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hz071/gcn-over-pruned-trees/model/gcn.py", line 27, in forward
    outputs, pooling_output = self.gcn_model(inputs)
  File "/home/hz071/.conda/envs/AG-GCNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hz071/gcn-over-pruned-trees/model/gcn.py", line 84, in forward
    adj = inputs_to_tree_reps(head.data, words.data, l, self.opt['prune_k'], subj_pos.data, obj_pos.data)
  File "/home/hz071/gcn-over-pruned-trees/model/gcn.py", line 78, in inputs_to_tree_reps
    trees = [head_to_tree(head[i], words[i], l[i], prune, subj_pos[i], obj_pos[i]) for i in range(len(l))]
  File "/home/hz071/gcn-over-pruned-trees/model/gcn.py", line 78, in <listcomp>
    trees = [head_to_tree(head[i], words[i], l[i], prune, subj_pos[i], obj_pos[i]) for i in range(len(l))]
  File "/home/hz071/gcn-over-pruned-trees/model/tree.py", line 81, in head_to_tree
    tmp += [h-1]
MemoryError

After that the implementation stopped.
Can you give me any idea what went wrong? I have used stanza pipeline(spacy tokenizer) for pre-processing.

**Comment by ZohaibRamzan** [comment]
Kindly someone from owner of this repo, please answer.
